config/routes.rb
Rails.application.routes.draw do
  resources :builds

end

app/models/build.rb
class Build < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:Foo, :bar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.erb
<%= form_for(@build) do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Foo %><br>
    <%= f.text_field :Foo %>
  </div>
  <div class="field">
    <%= f.label :bar %><br>
    <%= f.text_field :bar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form' %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builds</h1>

<table>
  <thead>
    <tr>
      <th>Foo</th>
      <th>Bar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.Foo %></td>
        <td><%= build.bar %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build', new_build_path %>

app/views/builds/new.html.erb
<h1>New Build</h1>

<%= render 'form' %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foo:</strong>
  <%= @build.Foo %>
</p>

<p>
  <strong>Bar:</strong>
  <%= @build.bar %>
</p>

<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PIDTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>